"""
Django settings for KlaireTestTech project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zgh&)ng0h@^opx_knyl9pvz&1a-v@+)aaw3+*%!w)z9*51du-)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    'rest_framework',
    'AddressManagement',
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = "KlaireTestTech.urls"

TEMPLATES = []

WSGI_APPLICATION = 'KlaireTestTech.wsgi.application'

# Database

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    db_name = DATABASE_URL.replace('sqlite:///', '')
else:
    db_name = BASE_DIR / 'data' / 'db.sqlite3'

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        'NAME': db_name,
    }
}




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
